// examples/vue/src/App.vue
<template>
  <div class="app">
    <h1>XGantt Vue 示例</h1>
    <div class="controls">
      <button @click="changePrimaryColor">切换主色调</button>
      <button @click="changeUnit">切换单位</button>
      <button @click="jumpToToday">跳转到今天</button>
      <button @click="addTask">添加任务</button>
      <button @click="refreshData">刷新数据</button>
    </div>

    <div class="gantt-wrapper">
      <XGanttVue
        ref="ganttRef"
        style="height: 400px; width: 800px"
        :options="{
          data: ganttData,
          table: tableConfig,
          chart: chartConfig,
          fields: fieldsConfig,
          links: linksConfig,
          primaryColor: primaryColor,
          unit: currentUnit,
          locale: 'zh',
          highlight: true,
          bar: {
            move: {
              enabled: true,
              single: {
                left: true,
                right: true
              }
            },
            progress: {
              show: true
            }
          }
        }"
        @move="onTaskMove"
        @select="onTaskSelect"
        @click:row="onRowClick"
        @dblclick:row="onRowDoubleClick"
        @error="onError"
        @create:link="addLink"
      />
    </div>

    <!-- 事件日志 -->
    <div class="event-log">
      <h3>事件日志</h3>
      <div class="log-content">
        <div v-for="(log, index) in eventLogs" :key="index" class="log-item">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-event">{{ log.event }}</span>
          <span class="log-data">{{ log.data }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from "vue";
import { type XGanttInstance, type IOptions } from "@xpyjs/gantt-vue";
import XGanttVue from "@xpyjs/gantt-vue";
import "@xpyjs/gantt-vue/style.css";

// 甘特图引用
const ganttRef = ref<XGanttInstance>();

// 事件日志
const eventLogs = ref<Array<{ time: string; event: string; data: string }>>([]);

// 添加日志
const addLog = (event: string, data: any) => {
  eventLogs.value.unshift({
    time: new Date().toLocaleTimeString(),
    event,
    data: JSON.stringify(data, null, 2)
  });

  // 保持最新 50 条记录
  if (eventLogs.value.length > 50) {
    eventLogs.value = eventLogs.value.slice(0, 50);
  }
};

// 甘特图数据
const ganttData = ref([
  {
    id: "1",
    name: "项目规划",
    startTime: "2024-01-01",
    endTime: "2024-01-15",
    progress: 80,
    children: [
      {
        id: "1-1",
        name: "需求分析",
        startTime: "2024-01-01",
        endTime: "2024-01-05",
        progress: 100
      },
      {
        id: "1-2",
        name: "技术选型",
        startTime: "2024-01-06",
        endTime: "2024-01-10",
        progress: 90
      },
      {
        id: "1-3",
        name: "架构设计",
        startTime: "2024-01-11",
        endTime: "2024-01-15",
        progress: 60
      }
    ]
  },
  {
    id: "2",
    name: "开发阶段",
    startTime: "2024-01-16",
    endTime: "2024-03-15",
    progress: 45,
    children: [
      {
        id: "2-1",
        name: "前端开发",
        startTime: "2024-01-16",
        endTime: "2024-02-15",
        progress: 70
      },
      {
        id: "2-2",
        name: "后端开发",
        startTime: "2024-01-20",
        endTime: "2024-02-20",
        progress: 60
      },
      {
        id: "2-3",
        name: "数据库设计",
        startTime: "2024-01-16",
        endTime: "2024-01-25",
        progress: 100
      },
      {
        id: "2-4",
        name: "接口联调",
        startTime: "2024-02-21",
        endTime: "2024-03-15",
        progress: 10
      }
    ]
  },
  {
    id: "3",
    name: "测试阶段",
    startTime: "2024-03-01",
    endTime: "2024-03-31",
    progress: 20,
    children: [
      {
        id: "3-1",
        name: "单元测试",
        startTime: "2024-03-01",
        endTime: "2024-03-10",
        progress: 50
      },
      {
        id: "3-2",
        name: "集成测试",
        startTime: "2024-03-11",
        endTime: "2024-03-20",
        progress: 20
      },
      {
        id: "3-3",
        name: "系统测试",
        startTime: "2024-03-21",
        endTime: "2024-03-31",
        progress: 0
      }
    ]
  },
  {
    id: "4",
    name: "上线部署",
    startTime: "2024-04-01",
    endTime: "2024-04-15",
    progress: 0
  }
]);

// 表格配置
const tableConfig = reactive<Required<IOptions>["table"]>({
  width: 300,
  columns: [
    {
      field: "name",
      label: "任务名称",
      width: 200,
      align: "left"
    },
    {
      field: "progress",
      label: "进度",
      width: 80,
      align: "center",
      render: row => {
        const p = `${row.data.progress || 0}%`;
        return `<div style="width: 100%; height: 20px; background: #f0f0f0; border-radius: 4px;">
                  <div style="width: ${p}; height: 100%; background: #1890ff; border-radius: 4px;"></div>
                </div>`;
      }
    },
    {
      field: "startTime",
      label: "开始时间",
      width: 120,
      align: "center"
    }
  ]
});

// 图表配置
const chartConfig = reactive({
  // show: true
});

// 字段配置
const fieldsConfig = reactive({
  id: "id",
  startTime: "startTime",
  endTime: "endTime",
  name: "name",
  progress: "progress",
  children: "children"
});

// 连线配置
const linksConfig = reactive({
  data: [
    { id: "link1", from: "1-1", to: "1-2", type: "FS" },
    { id: "link2", from: "1-2", to: "1-3", type: "FS" },
    { id: "link3", from: "1", to: "2", type: "FS" },
    { id: "link4", from: "2-3", to: "2-1", type: "FS" },
    { id: "link5", from: "2-3", to: "2-2", type: "FS" }
  ],
  key: "id",
  show: true,
  create: {
    enabled: true,
    mode: "hover" as const,
    radius: 3,
    width: 2,
    from: true,
    to: true
  },
  distance: 20,
  gap: 5,
  dash: [6, 3],
  width: 1,
  arrow: {
    width: 8,
    height: 8
  },
  radius: 3
});

// 事件处理函数
const onTaskMove = (moved: Array<{ row: any; old: any }>) => {
  addLog("任务移动", moved);
  console.log("任务移动:", moved);
};

const onTaskSelect = (selected: any[], checked: boolean, all: any[]) => {
  addLog("任务选择", { selected, checked, all });
  console.log("任务选择:", { selected, checked, all });
};

const onRowClick = (event: MouseEvent, row: any) => {
  addLog("行点击", { row: row.name });
  console.log("行点击:", row);
};

const onRowDoubleClick = (event: MouseEvent, row: any) => {
  addLog("行双击", { row: row.name });
  console.log("行双击:", row);
};

const onError = (error: any) => {
  addLog("错误", error);
  console.error("甘特图错误:", error);
};

const addLink = (link: any) => {
  link = { ...link, id: `link-${Date.now()}` }; // 自动生成唯一 ID
  addLog("添加连线", link);
  console.log("添加连线:", link);
  linksConfig.data.push(link);
};

// 操作函数
const jumpToToday = () => {
  const success = ganttRef.value?.getInstance()?.jumpTo();
  addLog("跳转到今天", { success });
};

const addTask = () => {
  const newTask = {
    id: `new-${Date.now()}`,
    name: `新任务 ${ganttData.value.length + 1}`,
    startTime: "2024-01-20",
    endTime: "2024-01-25",
    progress: 0
  };

  ganttData.value.push(newTask);
  addLog("添加任务", newTask);
};

const refreshData = () => {
  // 模拟刷新数据
  ganttData.value = [...ganttData.value];
  addLog("刷新数据", "数据已刷新");
};

const units = ["hour", "day", "week", "month", "quarter"] as const;
const currentUnit = ref<(typeof units)[number]>("day");
const changeUnit = () => {
  const currentIndex = units.indexOf(currentUnit.value);
  const newIndex = (currentIndex + 1) % units.length;
  const newUnit = units[newIndex];
  addLog("切换单位", { from: currentUnit.value, to: newUnit });
  currentUnit.value = newUnit;
};

const primaryColor = ref("#1890ff");
const changePrimaryColor = () => {
  const newColor = primaryColor.value === "#1890ff" ? "#52c41a" : "#1890ff";
  addLog("切换主色调", { from: primaryColor.value, to: newColor });
  primaryColor.value = newColor;
};
</script>

<style scoped>
.app {
  padding: 20px;
  font-family: "Arial", sans-serif;
}

h1 {
  color: #1890ff;
  margin-bottom: 20px;
}

.controls {
  margin-bottom: 20px;
}

.controls button {
  margin-right: 10px;
  padding: 8px 16px;
  border: 1px solid #1890ff;
  background: #1890ff;
  color: white;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.3s;
}

.controls button:hover {
  background: #40a9ff;
  border-color: #40a9ff;
}

.gantt-wrapper {
  margin-bottom: 30px;
  border: 1px solid #d9d9d9;
  border-radius: 6px;
  overflow: hidden;
}

.event-log {
  max-height: 300px;
  overflow: auto;
}

.event-log h3 {
  margin-bottom: 10px;
  color: #333;
}

.log-content {
  background: #f5f5f5;
  padding: 10px;
  border-radius: 4px;
  font-family: "Courier New", monospace;
  font-size: 12px;
}

.log-item {
  display: block;
  margin-bottom: 5px;
  padding: 5px;
  background: white;
  border-radius: 3px;
  border-left: 3px solid #1890ff;
}

.log-time {
  color: #666;
  margin-right: 10px;
}

.log-event {
  color: #1890ff;
  font-weight: bold;
  margin-right: 10px;
}

.log-data {
  color: #333;
}
</style>

// examples/react/src/App.tsx
import { useState, useCallback } from 'react';
import { XGanttReact, useXGantt } from '@xpyjs/gantt-react';
import type { IOptions } from '@xpyjs/gantt-react';
import "@xpyjs/gantt-react/style.css"
import AdvancedGanttExample from './AdvancedExample';

function App() {
    const [currentExample, setCurrentExample] = useState<'basic' | 'advanced'>('basic');

    // 如果选择高级示例，渲染高级组件
    if (currentExample === 'advanced') {
        return <AdvancedGanttExample />;
    }

    return <BasicGanttExample onSwitchExample={setCurrentExample} />;
}

// 基础示例组件
function BasicGanttExample({ onSwitchExample }: { onSwitchExample: (example: 'basic' | 'advanced') => void }) {
    const { ganttRef, jumpTo } = useXGantt();

    // 状态管理
    const [selectedTasks, setSelectedTasks] = useState<any[]>([]);
    const [lastClickedRow, setLastClickedRow] = useState<any>(null);
    const [primaryColor, setPrimaryColor] = useState('#007acc');
    const [currentUnit, setCurrentUnit] = useState<'day' | 'week' | 'month'>('day');
    const [eventLogs, setEventLogs] = useState<Array<{
        time: string;
        event: string;
        data: string;
    }>>([]);

    // 甘特图数据 - 使用状态管理以支持动态更新
    const [ganttData, setGanttData] = useState([
        {
            id: '1',
            name: '项目规划',
            startTime: '2025-05-01',
            endTime: '2025-05-15',
            progress: 80,
            children: [
                {
                    id: '1-1',
                    name: '需求分析',
                    startTime: '2025-05-01',
                    endTime: '2025-05-05',
                    progress: 100
                },
                {
                    id: '1-2',
                    name: '技术选型',
                    startTime: '2025-05-06',
                    endTime: '2025-05-10',
                    progress: 90
                }
            ]
        },
        {
            id: '2',
            name: '开发阶段',
            startTime: '2025-05-16',
            endTime: '2025-06-15',
            progress: 45,
            children: [
                {
                    id: '2-1',
                    name: '前端开发',
                    startTime: '2025-05-16',
                    endTime: '2025-06-15',
                    progress: 70
                },
                {
                    id: '2-2',
                    name: '后端开发',
                    startTime: '2025-05-20',
                    endTime: '2025-06-20',
                    progress: 60
                }
            ]
        }
    ]);

    // 添加日志
    const addLog = useCallback((event: string, data: any) => {
        setEventLogs(prev => [
            {
                time: new Date().toLocaleTimeString(),
                event,
                data: JSON.stringify(data, null, 2).slice(0, 100) + '...'
            },
            ...prev.slice(0, 49)
        ]);
    }, []);    // 事件处理器
    const handleSelect = useCallback((data: any[], checked: boolean, all: any[]) => {
        setSelectedTasks(all);
        addLog('任务选择', { selected: data.length, total: all.length, checked });
    }, [addLog]);

    const handleClickRow = useCallback((_e: MouseEvent, data: any) => {
        setLastClickedRow(data);
        addLog('行点击', { name: data.name, id: data.id });
    }, [addLog]);

    const handleDoubleClickRow = useCallback((_e: MouseEvent, data: any) => {
        addLog('行双击', { name: data.name, id: data.id });
    }, [addLog]);

    const handleMove = useCallback((data: { row: any; old: any }[]) => {
        addLog('任务移动', { count: data.length, tasks: data.map(d => d.row.name) });
        // 注意：在实际应用中，您可能需要根据移动的数据更新本地状态
        // 这里仅做演示，实际的数据同步可以通过回调或状态管理来处理
    }, [addLog]);

    const handleError = useCallback((error: any) => {
        addLog('错误', { message: error.message, type: error.type });
        console.error('甘特图错误:', error);
    }, [addLog]);

    const changePrimaryColor = useCallback(() => {
        const colors = ['#007acc', '#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4', '#feca57'];
        const currentIndex = colors.indexOf(primaryColor);
        const nextColor = colors[(currentIndex + 1) % colors.length];
        setPrimaryColor(nextColor);
        addLog('主色调切换', { color: nextColor });
    }, [primaryColor, addLog]);

    const changeUnit = useCallback(() => {
        const units: Array<'day' | 'week' | 'month'> = ['day', 'week', 'month'];
        const currentIndex = units.indexOf(currentUnit);
        const nextUnit = units[(currentIndex + 1) % units.length];
        setCurrentUnit(nextUnit);
        addLog('单位切换', { unit: nextUnit });
    }, [currentUnit, addLog]);

    const handleJumpToToday = useCallback(() => {
        const success = jumpTo(); // 不传参数，跳转到今天
        addLog('跳转到今天', { success });
    }, [jumpTo, addLog]);

    const handleJumpToDate = useCallback(() => {
        // 跳转到项目开始日期
        const success = jumpTo('2025-05-01');
        addLog('跳转到项目开始', { success, date: '2025-05-01' });
    }, [jumpTo, addLog]);

    const addTask = useCallback(() => {
        const newTask = {
            id: `new-${Date.now()}`,
            name: `新任务 ${Math.floor(Math.random() * 100)}`,
            startTime: '2025-06-01',
            endTime: '2025-06-10',
            progress: Math.floor(Math.random() * 100),
            children: [] // 确保有children属性
        };

        setGanttData(prev => [...prev, newTask]);
        addLog('添加任务', { name: newTask.name, id: newTask.id });
    }, [addLog]);

    const updateProgress = useCallback(() => {
        setGanttData(prev => prev.map(task => ({
            ...task,
            progress: Math.min(100, task.progress + Math.floor(Math.random() * 10)),
            children: task.children?.map(child => ({
                ...child,
                progress: Math.min(100, child.progress + Math.floor(Math.random() * 10))
            })) || []
        })));
        addLog('更新进度', { message: '所有任务进度已随机更新' });
    }, [addLog]);

    const resetData = useCallback(() => {
        // 重置为初始数据
        setGanttData([
            {
                id: '1',
                name: '项目规划',
                startTime: '2025-05-01',
                endTime: '2025-05-15',
                progress: 80,
                children: [
                    {
                        id: '1-1',
                        name: '需求分析',
                        startTime: '2025-05-01',
                        endTime: '2025-05-05',
                        progress: 100
                    },
                    {
                        id: '1-2',
                        name: '技术选型',
                        startTime: '2025-05-06',
                        endTime: '2025-05-10',
                        progress: 90
                    }
                ]
            },
            {
                id: '2',
                name: '开发阶段',
                startTime: '2025-05-16',
                endTime: '2025-06-15',
                progress: 45,
                children: [
                    {
                        id: '2-1',
                        name: '前端开发',
                        startTime: '2025-05-16',
                        endTime: '2025-06-15',
                        progress: 70
                    },
                    {
                        id: '2-2',
                        name: '后端开发',
                        startTime: '2025-05-20',
                        endTime: '2025-06-20',
                        progress: 60
                    }
                ]
            }
        ]);
        addLog('重置数据', { message: '数据已重置为初始状态' });
    }, [addLog]);

    // 甘特图配置 - 配置会自动更新到甘特图组件
    const ganttOptions: IOptions = {
        data: ganttData,
        table: {
            width: 300,
            columns: [
                {
                    field: 'name',
                    label: '任务名称',
                    width: 200,
                    align: 'left'
                },
                {
                    field: 'progress',
                    label: '进度',
                    width: 100,
                    align: 'center'
                }
            ]
        },
        fields: {
            id: 'id',
            name: 'name',
            startTime: 'startTime',
            endTime: 'endTime',
            progress: 'progress',
            children: 'children'
        },
        primaryColor,
        unit: currentUnit,
        locale: 'zh',
        highlight: true,
        selection: {
            enabled: true
        },
        bar: {
            move: {
                enabled: true,
                byUnit: true
            }
        }
    };

    return (
        <div className="app">
            <h1>XGantt React 基础示例</h1>

            <div className="controls">
                <button
                    onClick={() => onSwitchExample('basic')}
                    style={{ backgroundColor: '#005a9e' }}
                >
                    基础示例
                </button>
                <button
                    onClick={() => onSwitchExample('advanced')}
                    style={{ backgroundColor: '#007acc' }}
                >
                    高级示例
                </button>
                <button onClick={changePrimaryColor}>
                    切换主色调 ({primaryColor})
                </button>
                <button onClick={changeUnit}>
                    切换单位 ({currentUnit})
                </button>
                <button onClick={handleJumpToToday}>
                    跳转到今天
                </button>
                <button onClick={handleJumpToDate}>
                    跳转到项目开始
                </button>
                <button onClick={addTask}>
                    添加任务
                </button>
                <button onClick={updateProgress}>
                    更新进度
                </button>
                <button onClick={resetData}>
                    重置数据
                </button>
            </div>

            <div className="responsive-grid">
                <div className="gantt-wrapper">
                    <XGanttReact
                        ref={ganttRef}
                        style={{ height: '500px', width: '100%' }}
                        options={ganttOptions}
                        onSelect={handleSelect}
                        onClickRow={handleClickRow}
                        onDoubleClickRow={handleDoubleClickRow}
                        onMove={handleMove}
                        onError={handleError}
                    />
                </div>

                <div className="info-panel">
                    <h3>实时信息</h3>

                    <div className="info-section">
                        <h4>选中状态</h4>
                        <div className="info-content">
                            已选择 {selectedTasks.length} 个任务
                            {lastClickedRow && (
                                <div>最后点击: {lastClickedRow.name}</div>
                            )}
                        </div>
                    </div>

                    <div className="info-section">
                        <h4>配置信息</h4>
                        <div className="info-content">
                            <div>主色调: {primaryColor}</div>
                            <div>显示单位: {currentUnit}</div>
                            <div>任务总数: {ganttData.length}</div>
                            <div>子任务总数: {ganttData.reduce((sum, task) => sum + (task.children?.length || 0), 0)}</div>
                        </div>
                    </div>

                    <div className="info-section">
                        <h4>API 使用说明</h4>
                        <div className="info-content">
                            <div>• useXGantt: 获取 ganttRef, jumpTo</div>
                            <div>• 配置自动更新: 修改 options 自动同步</div>
                            <div>• jumpTo(): 跳转到今天</div>
                            <div>• jumpTo(date): 跳转到指定日期</div>
                        </div>
                    </div>

                    <div className="info-section">
                        <h4>事件日志</h4>
                        <div className="event-log">
                            {eventLogs.map((log, index) => (
                                <div key={index} className="log-item">
                                    <span className="log-time">{log.time}</span>
                                    <span className="log-event">{log.event}</span>
                                    <span className="log-data">{log.data}</span>
                                </div>
                            ))}
                            {eventLogs.length === 0 && (
                                <div className="info-content">暂无事件，开始操作甘特图吧！</div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default App;
